# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Qlty coverage reporter

on:
  push:
    branches: 
      - main
jobs:
  qlty-coverage-reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ${{ github.workspace }}/lcov.info
      # - name: Notify actions to slack(pgv-inc-notification.slack.com)
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      #     author_name: ${{ github.actor }}
      #   env:
      #     # pgv-inc-notification.slack.com#github-actions)
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
