# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Qlty coverage reporter

on:
  push:
    branches: 
      - main
jobs:
  qlty-coverage-reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ${{ github.workspace }}/lcov.info
        if: always()
